apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-deployment
  name: jenkins-deployment
spec:
  ports:
  - port: 8080
    nodePort: 32000
    targetPort: 8080
  selector:
    app: jenkins-deployment
  type: NodePort
